foodApp_django/food/urls.py
from django.urls import path, include

from . import views

app_name = 'food'

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("add", views.AddItemView.as_view(), name="add"),
    path("update/<int:pk>", views.update_item, name="update_item"),
    path("delete/<int:id>", views.delete_item, name="delete"),
    path("<int:pk>", views.DetailFoodView.as_view(), name="detail"),
]

foodApp_django/foodApp_django/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from django.views.generic.base import RedirectView

from users import views as user_views
from django.contrib.auth import views as authentication_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("food/", include("food.urls")),
    path("", RedirectView.as_view(url="/food/")),
    path("users/", include("users.urls")),
    ## Register, Login, Logout
    path("register/", user_views.register, name="register"),
    path("login/", authentication_views.LoginView.as_view(template_name="user/login.html"), name="login"),
    path('logout/', authentication_views.LogoutView.as_view(template_name="user/logout.html"), name='logout'),
    ## Profile
    path("profile/", user_views.profilepage, name="profile")
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodApp_django/users/urls.py
from django.urls import path, include

from . import views
from django.contrib.auth import views as authentication_views

app_name = 'users'

urlpatterns = [
    
]

foodApp_django/food/models.py
from django.db import models
from django.contrib.auth.models import User

from django.urls import reverse

# Create your models here.
class Item(models.Model):
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=250)
    item_price = models.IntegerField()
    image = models.ImageField(upload_to="images", null=True)
    
    def __str__(self):
        return self.item_name
    
    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})
    

foodApp_django/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="profile_pics/", default="profile_pics/default.png")
    location = models.CharField(max_length=100)
    
    def __str__(self):
        return self.user.username

foodApp_django/food/forms.py
from django import forms

from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["item_name", "item_desc", "item_price", "image"]

foodApp_django/users/forms.py
from django import forms

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

foodApp_django/food/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy

from .models import Item
from .forms import ItemForm

from django.views.generic import ListView, DetailView, CreateView
# Create your views here.
class IndexView(ListView):
    model = Item
    template_name = "food/food.html"
    context_object_name = "items"
    
class DetailFoodView(DetailView):
    model = Item
    template_name = "food/food_detail.html"
    context_object_name = "item"

class AddItemView(CreateView):
    model = Item
    fields = ["item_name", "item_desc", "item_price", "image"]
    template_name = "food/item_form.html"
    
    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)

def update_item(request, id):
    item = get_object_or_404(Item, id=id)
    
    if request.method == 'POST':
        form = ItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect("food:index")
    else:
        form = ItemForm(instance=item)  # This line should only execute for GET requests
    
    return render(request, "food/item_form.html", {"form": form, "item": item})

def delete_item(request, id):
    item = get_object_or_404(Item, id=id)
    
    if request.method == "POST":
        item.delete()
        return redirect("food:index")
    return render(request, "food/item_delete.html", {"item":item})

foodApp_django/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .forms import RegisterForm
from .models import Profile

from django.views.generic import ListView

# Create your views here.
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"Welcome {username}, your are now logged in!")
            return redirect("login")
    else:
        form = RegisterForm()
    return render(request, "user/register.html", {"form": form})

@login_required
def profilepage(request):
    profile = Profile()
    return render(request, "user/profile.html", {"profile": profile})



foodApp_django/food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "food/styles.css" %}">
    {% block css_files %}{% endblock %}
    {% block title %}{% endblock %}
</head>
<body>
  <nav class="navbar">
    <div class="navbar-logo">
        <a href="{% url "food:index" %}">FoodApp</a>
    </div>
    <ul class="navbar-links">
        <li><a class="link" href="{% url "food:add" %}">Add Item</a></li>
        <li><a class="link" href="#">Delete Item</a></li>
        <li><a class="link" href="#">View Item</a></li>
        {% if user.is_authenticated %}
        <li><a class="link" href="{% url "profile" %}">Profile</a></li>
        <li>
            <!-- Other navigation links -->
            <form method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button class="logout" type="submit">Log Out</button>
            </form>
        </li>
        {% else %}
            <li><a class="login" href="{% url "login" %}">Log In</a></li>
        {% endif %}
    </ul>
</nav>

<div class="messages">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
</div>
{% block content %}{% endblock %}
</body>
</html>

foodApp_django/food/templates/food/food.html
{% extends "food/base.html" %}
{% load static %}

{% block css_files %}<link rel="stylesheet" href="{% static "food/food.css" %}">{% endblock %}
{% block title %}
    <title>FoodApp</title>
{% endblock %}

{% block content %}
<section>
    {% for item in items %}
    <div class="card">
        <img src="{{item.image.url}}" alt="Card Image" class="card-img">
        <div class="card-content">
            <h2 class="card-title">{{item.item_name}}</h2>
            <a href="{% url "food:detail" item.id %}" class="card-btn">Learn More</a>
            <p class="posted">"Posted By {{item.user_name | title}}"</p>
        </div>
    </div>
    {% endfor %}
</section>

{% endblock %}

foodApp_django/food/templates/food/food_detail.html
{% extends "food/base.html" %}
{% load static %}

{% block css_files %}<link rel="stylesheet" href="{% static "food/food_detail.css" %}">{% endblock %}
{% block title %}
    <title>FoodApp</title>
{% endblock %}

{% block content %}
<section class="item-detail">
    <div class="item-content">
        <img src="{{ item.image.url }}" alt="{{ item.item_name }}" class="item-img">
        <h1 class="item-title">{{ item.item_name }}</h1>
        <p class="item-desc">{{ item.item_desc }}</p>
        <p class="item-price">Price: ${{ item.item_price }}</p>
        <p class="posted">"Posted By {{item.user_name | title}}"</p>

        <a href="{% url "food:delete" item.id %}">Delete Item</a>
    </div>
</section>
{% endblock %}

foodApp_django/food/templates/food/item_delete.html
{% extends "food/base.html" %}
{% load static %}

{% block css_files %}<link rel="stylesheet" href="{% static "food/item_delete.css" %}">{% endblock %}
{% block title %}
    <title>FoodApp</title>
{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <h2>Are you sure that you want to delete "{{item.item_name | title}}"</h2>
        <button>Confirm</button>
    </form>
{% endblock %}

foodApp_django/food/templates/food/item_form.html
{% extends "food/base.html" %}
{% load static %}

{% block css_files %}<link rel="stylesheet" href="{% static "food/item_form.css" %}">{% endblock %}
{% block title %}
    <title>FoodApp</title>
{% endblock %}

{% block content %}
<div class="container">
    <h1>Add Item</h1>
    <form method="POST" enctype="multipart/form-data" class="form">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn">Submit</button>
    </form>
</div>

{% endblock %}

foodApp_django/users/templates/user/login.html
{% extends "food/base.html" %}
{% load static %}

{% block css_files %}<link rel="stylesheet" href="{% static "user/login.css" %}">{% endblock %}
{% block title %}
    <title>FoodApp</title>
{% endblock %}

{% block content %}
<section>
    <div class="login-container">
      <h1>Log In</h1>
      <form method="POST">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit">Log In</button>
      </form>
    </div>
  </section>
{% endblock %}

foodApp_django/users/templates/user/logout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static "user/logout.css" %}">
  </head>
  <body>
    <div class="message-container">
      <h1>You have been logged out</h1>
      <a href="{% url 'login' %}">Log In</a>
    </div>
  </body>
</html>

foodApp_django/users/templates/user/profile.html
{% extends "food/base.html" %}
{% load static %}

{% block css_files %}<link rel="stylesheet" href="{% static "food/item_delete.css" %}">{% endblock %}
{% block title %}
    <title>FoodApp</title>
{% endblock %}

{% block content %}
    <h1>{{user.username}}</h1>
    <img width="400px" src="{{user.profile.image.url}}">
{% endblock %}

foodApp_django/users/templates/user/register.html
{% extends "food/base.html" %}
{% load static %}

{% block css_files %}<link rel="stylesheet" href="{% static "user/register.css" %}">{% endblock %}
{% block title %}
    <title>FoodApp</title>
{% endblock %}

{% block content %}
  <section>
    <div class="container">
      <h1>Register</h1>
      <form method="POST" class="register-form">
        {% csrf_token %} {% for field in form %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
          {{ field }} {% for error in field.errors %}
          <div class="error">{{ error }}</div>
          {% endfor %}
        </div>
        {% endfor %}
        <button type="submit" class="btn">Register</button>
      </form>
    </div>
  </section>
{% endblock %}